data_settings:
  dataset_path: "/content/drive/MyDrive/open-domain-chatbot-with-rag/dataset/merged_pairs.json"
  glove_path: "/content/drive/MyDrive/open-domain-chatbot-with-rag/glove/glove.6B.300d.txt"
  vocab_path: "/content/drive/MyDrive/open-domain-chatbot-with-rag/dataset/vocab.pkl"
  min_freq: 2
  max_len: 50

model_settings:
  emb_dim: 300
  hidden_dim: 256
  n_heads: 6
  n_layers: 4         
  dropout: 0.2
  pad_idx: 0

train_settings:
  batch_size: 64
  num_epochs: 5
  learning_rate: 0.0005
  weight_decay: 1e-5
  clip_grad: 1.0
  early_stopping_patience: 3

experiment_settings:
  experiment_name: "transformer3"
  project: "open_domain_chatbot"
  use_wandb: false

