data_settings:
  dataset_path: "/path/to/merged_pairs.json"
  glove_path: "/path/to/glove.6B.300d.txt"
  vocab_path: "/path/to/vocab.pkl"
  min_freq: 2
  max_len: 50

model_settings:
  emb_dim: 300
  hidden_dim: 512
  n_heads: 4
  n_layers: 2
  dropout: 0.3
  pad_idx: 0

train_settings:
  batch_size: 64
  num_epochs: 5
  learning_rate: 0.0005
  weight_decay: 1e-5
  clip_grad: 1.0
  early_stopping_patience: 3

experiment_settings:
  experiment_name: "transformer1"
  project: "open_domain_chatbot"
  use_wandb: false

